"""MP4 -> frames -> SAM3 bg removal, writing data/query/high/<task>/*.png.

Two modes (auto-detected from video_root layout):

  Single-video mode  (video_root/<task>.mp4, default frames_per_video=50):
      python postprocess.py --video_root .../query/high --frames_root ... --out_root ...

  Multi-video mode  (video_root/<task>/v0000.mp4 ... v0009.mp4, generated by
                     generate.py --n_per_task N, default frames_per_video=5):
      python postprocess.py --video_root .../query/gr00t \
          --frames_root ... --out_root ... --frames_per_video 5

  Output frame names:
    single-video:  <task>/frame_NNNN.png
    multi-video:   <task>/v{vid:04d}_f{frame:02d}.png

Resume-safe: skips an output PNG if it already exists.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Wire reusable utilities onto sys.path before importing.
# - extract_frames.py lives at <repo>/scripts/
# - sam3.py lives at <repo>/../sam3.py (parent of repo, calibration/feepe/)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[1]              # feature_matching_eval_hallucination/
PARENT    = REPO_ROOT.parent                                  # calibration/feepe/
# Insert in reverse so scripts/ ends up FIRST in sys.path.
# (outer feepe/extract_frames.py is a stale older variant; we want repo/scripts/.)
for p in (PARENT, REPO_ROOT, REPO_ROOT / "scripts"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from extract_frames import extract_uniform                    # noqa: E402  (reuse)
from sam3 import SAM3Segmenter, PROMPTS                       # noqa: E402  (reuse)
from tqdm import tqdm                                          # noqa: E402


# ---------------------------------------------------------------------------
# Harvester
# ---------------------------------------------------------------------------
class QueryHighHarvester:
    """
    Two modes based on video_root layout:

    Single-video:  video_root/<task>.mp4
    Multi-video:   video_root/<task>/v0000.mp4  v0001.mp4  ...

    Staging (frames_root):
      single-video:  frames_root/<task>/frame_NNNN.png
      multi-video:   frames_root/<task>/v{vid:04d}/frame_NNNN.png

    Output (out_root):
      single-video:  out_root/<task>/frame_NNNN.png
      multi-video:   out_root/<task>/v{vid:04d}_f{frame:02d}.png
    """

    def __init__(
        self,
        video_root: Path,
        frames_root: Path,
        out_root: Path,
        frames_per_video: int = 50,
        sam3_threshold: float = 0.3,
        prompts: list[str] | None = None,
    ) -> None:
        self.video_root = Path(video_root)
        self.frames_root = Path(frames_root)
        self.out_root = Path(out_root)
        self.frames_per_video = frames_per_video
        self.sam3_threshold = sam3_threshold
        self.prompts = list(prompts) if prompts is not None else list(PROMPTS)

        self.frames_root.mkdir(parents=True, exist_ok=True)
        self.out_root.mkdir(parents=True, exist_ok=True)

        # Detect mode once
        self._multi_video = self._detect_multi_video()

    def _detect_multi_video(self) -> bool:
        """Return True if video_root contains <task>/ subdirectories with MP4s."""
        for p in self.video_root.iterdir():
            if p.is_dir() and any(p.glob("*.mp4")):
                return True
        return False

    # -- public ---------------------------------------------------------

    def run(self) -> None:
        mode = "multi-video" if self._multi_video else "single-video"
        print(f"[postprocess] mode={mode}  frames_per_video={self.frames_per_video}")
        self._extract_all()
        self._remove_bg_all()

    # -- step 1: video -> raw PNGs -------------------------------------

    def _extract_all(self) -> None:
        if self._multi_video:
            self._extract_multi()
        else:
            self._extract_single()

    def _extract_single(self) -> None:
        """video_root/<task>.mp4  ->  frames_root/<task>/frame_NNNN.png"""
        mp4s = sorted(self.video_root.glob("*.mp4"))
        if not mp4s:
            print(f"[postprocess] WARN: no MP4s in {self.video_root}")
            return
        total = 0
        print(f"[postprocess] extract (single): {len(mp4s)} videos -> {self.frames_root}")
        for mp4 in mp4s:
            task = mp4.stem
            task_dir = self.frames_root / task
            n = extract_uniform(mp4, task_dir, self.frames_per_video)
            total += n
            print(f"  {n:3d} frames  {task[:70]}")
        print(f"[postprocess] extracted {total} frames total")

    def _extract_multi(self) -> None:
        """video_root/<task>/v*.mp4  ->  frames_root/<task>/v{idx:04d}/frame_NNNN.png"""
        task_dirs = sorted(d for d in self.video_root.iterdir() if d.is_dir())
        if not task_dirs:
            print(f"[postprocess] WARN: no task subdirs in {self.video_root}")
            return
        total = 0
        print(f"[postprocess] extract (multi): {len(task_dirs)} tasks -> {self.frames_root}")
        for task_dir in task_dirs:
            task = task_dir.name
            mp4s = sorted(task_dir.glob("v*.mp4"))
            if not mp4s:
                print(f"  WARN: no v*.mp4 in {task_dir}")
                continue
            for vid_idx, mp4 in enumerate(mp4s):
                staging = self.frames_root / task / f"v{vid_idx:04d}"
                n = extract_uniform(mp4, staging, self.frames_per_video)
                total += n
            print(f"  {len(mp4s)} videos × {self.frames_per_video} frames  {task[:60]}")
        print(f"[postprocess] extracted {total} frames total")

    # -- step 2: raw PNG -> SAM3 bg-removed PNG -------------------------

    def _remove_bg_all(self) -> None:
        if self._multi_video:
            self._remove_bg_multi()
        else:
            self._remove_bg_single()

    def _remove_bg_single(self) -> None:
        """frames_root/<task>/frame_NNNN.png  ->  out_root/<task>/frame_NNNN.png"""
        task_dirs = sorted(d for d in self.frames_root.iterdir() if d.is_dir())
        if not task_dirs:
            print(f"[postprocess] WARN: no per-task frame dirs in {self.frames_root}")
            return
        seg: SAM3Segmenter | None = None
        for task_dir in task_dirs:
            out_task = self.out_root / task_dir.name
            out_task.mkdir(parents=True, exist_ok=True)
            pngs = sorted(task_dir.glob("*.png"))
            pending = [p for p in pngs if not (out_task / p.name).exists()]
            if not pending:
                print(f"[postprocess] skip (all done): {task_dir.name}")
                continue
            seg = seg or self._load_seg()
            print(f"[postprocess] bg-remove: {task_dir.name}  ({len(pending)} frames)")
            for png in tqdm(pending, desc=task_dir.name[:40], leave=False):
                self._process_one(seg, png, out_task / png.name)

    def _remove_bg_multi(self) -> None:
        """
        frames_root/<task>/v{idx:04d}/frame_NNNN.png
          ->  out_root/<task>/v{idx:04d}_f{frame_num:02d}.png
        """
        task_dirs = sorted(d for d in self.frames_root.iterdir() if d.is_dir())
        if not task_dirs:
            print(f"[postprocess] WARN: no per-task staging dirs in {self.frames_root}")
            return
        seg: SAM3Segmenter | None = None
        for task_dir in task_dirs:
            task = task_dir.name
            out_task = self.out_root / task
            out_task.mkdir(parents=True, exist_ok=True)
            vid_subdirs = sorted(d for d in task_dir.iterdir() if d.is_dir() and d.name.startswith("v"))
            for vid_subdir in vid_subdirs:
                vid_tag = vid_subdir.name          # e.g. "v0003"
                pngs = sorted(vid_subdir.glob("*.png"))
                pending = []
                for frame_num, png in enumerate(pngs):
                    out_name = f"{vid_tag}_f{frame_num:02d}.png"
                    if not (out_task / out_name).exists():
                        pending.append((frame_num, png))
                if not pending:
                    continue
                seg = seg or self._load_seg()
                for frame_num, png in tqdm(
                    pending, desc=f"{task[:30]}/{vid_tag}", leave=False
                ):
                    out_name = f"{vid_tag}_f{frame_num:02d}.png"
                    self._process_one(seg, png, out_task / out_name)

    # -- helpers --------------------------------------------------------

    def _load_seg(self) -> SAM3Segmenter:
        print("[postprocess] loading SAM3...")
        return SAM3Segmenter()

    def _process_one(self, seg: SAM3Segmenter, src: Path, dst: Path) -> None:
        try:
            alpha = seg.segment_multi_prompt(src, self.prompts, threshold=self.sam3_threshold)
            if alpha is None:
                shutil.copyfile(src, dst)
                return
            seg.remove_background(src, alpha).save(dst)
        except Exception as e:
            print(f"  [warn] {src.name}: {e}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser(
        description="MP4 -> frames -> SAM3 bg removal. Auto-detects single vs multi-video layout."
    )
    ap.add_argument("--video_root", required=True, type=Path,
                    help="Dir with <task>.mp4 (single) or <task>/v*.mp4 (multi).")
    ap.add_argument("--frames_root", required=True, type=Path,
                    help="Staging dir for raw extracted PNGs.")
    ap.add_argument("--out_root", required=True, type=Path,
                    help="Final output dir (bg removed).")
    ap.add_argument("--frames_per_video", type=int, default=50,
                    help="Frames to sample per video (default 50; use 5 for multi-video).")
    ap.add_argument("--sam3_threshold", type=float, default=0.3)
    args = ap.parse_args()
    QueryHighHarvester(
        video_root=args.video_root,
        frames_root=args.frames_root,
        out_root=args.out_root,
        frames_per_video=args.frames_per_video,
        sam3_threshold=args.sam3_threshold,
    ).run()


if __name__ == "__main__":
    main()
