#!/usr/bin/env python3
"""Create + populate the wmbench HF dataset (twanghcmut/wmbench).

Structure (extensible — add new world-model benchmarks later as siblings):

    twanghcmut/wmbench/
      README.md
      gr-1/
        README.md
        training/<task>.mp4
        generated/<task>/v0000.mp4 ... v0004.mp4
        reference/<task>/frame_NNNN.png          (SAM3-segmented)
        null_per_task/<task>.npz                  (cached null distributions)
        results/
          per_task_dense_table.csv
          per_task_ratio_table.csv
          per_task_ratio_ranking.md
          viz/                                   (all viz outputs)
        method.md                                (copy of WARPDYN_METHOD.md)

Future:
      droid/                                     (next dataset)

Usage (groot env):
    python scripts/upload_wmbench.py [--skip_create]
"""
from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path("/mnt/data/sftp/data/quangpt3/gcvwm/calibration/feepe/feature_matching_eval_hallucination")
WORKTREE_ROOT = Path("/mnt/data/sftp/data/quangpt3/gcvwm/calibration/feepe/feature_matching_eval_hallucination/.claude/worktrees/feat-knn-pool-gr1")
BENCH = REPO_ROOT / "paper-physical-gr1"

HF_REPO = "twanghcmut/wmbench"
HF_GR1_PREFIX = "gr-1"

EVAL_TASKS_FULL = [
    "1_Use the right hand to pick up green bok choy from tan table right side to bottom level of wire basket.",
    "2_Use the right hand to pick up rubik's cube from top level of the shelf to bottom level of the shelf.",
    "3_Use the right hand to pick up banana from teal plate to wooden table.",
    "4_Use the left hand to pick up dragonfruit from pink plate to teal plate.",
    "6_Use the right hand to pick up orange from middle of table to bottom white shelf.",
]


def task_short(task_full: str) -> str:
    return f"task_{task_full.split('_')[0]}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip_create", action="store_true",
                    help="Skip create_repo (set if repo already exists)")
    args = ap.parse_args()

    from huggingface_hub import HfApi
    token = (Path.home() / ".cache" / "huggingface" / "token").read_text().strip()
    api = HfApi(token=token)

    # ── Create new dataset repo
    if not args.skip_create:
        try:
            api.create_repo(repo_id=HF_REPO, repo_type="dataset",
                            private=False, exist_ok=True)
            print(f"Repo ready: https://huggingface.co/datasets/{HF_REPO}")
        except Exception as e:
            print(f"create_repo: {e}")

    # ── Top-level README
    top_readme = f"""---
license: cc-by-4.0
language:
  - en
tags:
  - robotics
  - video
  - hallucination-detection
  - world-models
pretty_name: WMBench — World-Model video benchmark for hallucination detection
---

# WMBench

Benchmark suite for evaluating **hallucination / anomaly detection** on
video generated by world models (Cosmos, OpenSora, etc.) against real
robot training distributions.

## Datasets

| Dataset | Source | Tasks | Videos |
|---|---|---|---|
| `gr-1/`  | NVIDIA GR1 (`PhysicalAI-Robotics-GR00T-GR1`) | 5 eval tasks | 5 real + 24 Cosmos gens |
| `droid/` (planned) | Stanford DROID | — | — |

Each dataset folder contains:

- `training/`        Real training mp4s (one per task)
- `generated/`       World-model generated mp4s, grouped by task
- `reference/`       50 SAM3-segmented PNG frames per task (for null calibration)
- `null_per_task/`   Pre-computed cycle null distributions (.npz)
- `results/`         WarpDyn scores, ranking, visualizations
- `method.md`        Per-dataset method notes / reproducibility

## Method: WarpDyn

Pure feature-matching anomaly detector using RoMa cycle composition error,
per-task multi-lag null distribution, and per-task ratio scoring.

See [`gr-1/method.md`](gr-1/method.md) for the full step-by-step method.
"""
    tmp = Path(tempfile.mkdtemp(prefix="wmbench_"))
    (tmp / "README.md").write_text(top_readme)
    api.upload_file(path_or_fileobj=str(tmp / "README.md"),
                    path_in_repo="README.md",
                    repo_id=HF_REPO, repo_type="dataset")
    print("Uploaded: README.md (top-level)")

    # ── GR-1 README
    gr1_readme = """# GR-1 dataset

Robot videos from NVIDIA's `nvidia/PhysicalAI-Robotics-GR00T-GR1`,
plus Cosmos Predict-2 generated videos.

## Layout

```
gr-1/
├── training/                          5 real .mp4 (one per task)
├── generated/                         24 Cosmos gens (5 tasks × ~5 vids)
│   ├── task_1/v0000.mp4 ... v0004.mp4
│   └── ...
├── reference/                         50 SAM3-segmented PNG frames per task
│   └── task_<N>/frame_NNNN.png
├── null_per_task/                     Cached cycle null distributions
│   └── task_<N>.npz                   (~5 KB each)
├── results/
│   ├── per_task_dense_table.csv       Raw H scores per video
│   ├── per_task_ratio_table.csv       Ranked by ratio
│   ├── per_task_ratio_ranking.md      Markdown report
│   └── viz/                           All visualizations
│       ├── INDEX.md
│       ├── overview_ranking.png       24-cell poster
│       ├── per_video/<rank>_*/        Summary card per gen
│       └── per_task_comparison/       Real vs gens side-by-side
└── method.md                          WarpDyn method documentation
```

## Tasks (5 evaluated)

| ID | Description |
|---|---|
| 1 | Pick up green bok choy from tan table to wire basket |
| 2 | Pick up rubik's cube from top shelf to bottom shelf |
| 3 | Pick up banana from teal plate to wooden table |
| 4 | Pick up dragonfruit from pink plate to teal plate |
| 6 | Pick up orange from middle of table to bottom white shelf |

## Results summary

| Metric | Value |
|---|---|
| Real max H_peak (cycle) | 0.832 |
| Threshold @ FPR=0% | 0.832 (global), per-task ratio = 1.0 |
| Gen catch (ratio > 1.0) | **18/24** (75%) |
| AUROC | 0.77 |
"""
    (tmp / "gr1_README.md").write_text(gr1_readme)
    api.upload_file(path_or_fileobj=str(tmp / "gr1_README.md"),
                    path_in_repo=f"{HF_GR1_PREFIX}/README.md",
                    repo_id=HF_REPO, repo_type="dataset")
    print(f"Uploaded: {HF_GR1_PREFIX}/README.md")

    # ── Method doc
    method_src = WORKTREE_ROOT / "WARPDYN_METHOD.md"
    api.upload_file(path_or_fileobj=str(method_src),
                    path_in_repo=f"{HF_GR1_PREFIX}/method.md",
                    repo_id=HF_REPO, repo_type="dataset")
    print(f"Uploaded: {HF_GR1_PREFIX}/method.md")

    # ── Training videos (5 real)
    print("\nUploading training videos …")
    for task_full in EVAL_TASKS_FULL:
        num = task_full.split("_")[0]
        src = BENCH / "raw_videos" / "gr1" / f"{num}.mp4"
        dst = f"{HF_GR1_PREFIX}/training/{task_short(task_full)}.mp4"
        if src.exists():
            api.upload_file(path_or_fileobj=str(src), path_in_repo=dst,
                            repo_id=HF_REPO, repo_type="dataset")
            print(f"  {dst}")

    # ── Generated videos (24)
    print("\nUploading generated videos …")
    for task_full in EVAL_TASKS_FULL:
        gen_dir = BENCH / "generated" / task_full
        for mp4 in sorted(gen_dir.glob("v*.mp4")):
            dst = f"{HF_GR1_PREFIX}/generated/{task_short(task_full)}/{mp4.name}"
            api.upload_file(path_or_fileobj=str(mp4), path_in_repo=dst,
                            repo_id=HF_REPO, repo_type="dataset")
            print(f"  {dst}")

    # ── Reference SAM3-segmented frames (50 × 5 = 250)
    print("\nUploading reference SAM3 frames …")
    for task_full in EVAL_TASKS_FULL:
        ref_dir = BENCH / "reference" / task_full
        if not ref_dir.exists():
            continue
        ts = task_short(task_full)
        # Upload as folder (faster than one-by-one)
        api.upload_folder(
            folder_path=str(ref_dir),
            path_in_repo=f"{HF_GR1_PREFIX}/reference/{ts}",
            repo_id=HF_REPO, repo_type="dataset",
        )
        print(f"  {HF_GR1_PREFIX}/reference/{ts}/  ({len(list(ref_dir.glob('*.png')))} files)")

    # ── Results: CSVs + markdown
    print("\nUploading results …")
    eval_dir = BENCH / "per_task_dense_eval"
    for name in ["per_task_dense_table.csv",
                 "per_task_ratio_table.csv",
                 "per_task_ratio_ranking.md"]:
        src = eval_dir / name
        if src.exists():
            api.upload_file(path_or_fileobj=str(src),
                            path_in_repo=f"{HF_GR1_PREFIX}/results/{name}",
                            repo_id=HF_REPO, repo_type="dataset")
            print(f"  results/{name}")

    # ── Visualization gallery
    viz_dir = BENCH / "viz"
    if viz_dir.exists():
        print("\nUploading viz/ gallery …")
        api.upload_folder(
            folder_path=str(viz_dir),
            path_in_repo=f"{HF_GR1_PREFIX}/results/viz",
            repo_id=HF_REPO, repo_type="dataset",
        )
        print(f"  results/viz/  ({sum(1 for _ in viz_dir.rglob('*.png'))} PNG, "
              f"{sum(1 for _ in viz_dir.rglob('*.md'))} MD)")
    else:
        print(f"\n[skip] viz dir not found: {viz_dir}")

    print(f"\n=== Done ===")
    print(f"Repo: https://huggingface.co/datasets/{HF_REPO}")
    print(f"GR-1: https://huggingface.co/datasets/{HF_REPO}/tree/main/{HF_GR1_PREFIX}")


if __name__ == "__main__":
    main()
